name: ZZU COMMUTE HELPERA

on:
    workflow_dispatch:
    schedule:
    - cron: '0 20 * * *'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Check
        uses: actions/checkout@v2
    
      - name: Run
        env:
            UID: ${{secrets.UID1}}
            UPW: ${{secrets.UPW1}}
        run: bash ./script.sh $UID $UPW
